### ISSUE TITLE
Information on usage permissions

### ISSUE THREAD

**Issue by DrUsamaN** [mustafa0x/quran-morphology#2]
AsSalaamu 'Alaykum wa Rahmatu Allaahi wa barakaatuh,

Is it allowed to use the files from this project inside other projects please? 
And is it possible and allowed to get the .svg files of the i'raab graphs on furqan.co please?

**Comment by mustafa0x** [comment]
وعليكم السلام ورحمة الله وبركاته
Yes, it is allowed. We do ask that the projects be free from ads.

As for the iraab graphs, we are still working on them.

**Comment by DrUsamaN** [comment]
جزاك الله خيرا يا أخي
